[package]
name = "bench"
version = "0.0.0"
publish = false
edition = "2021"

[[bench]]
name = "bench"
harness = false

[dependencies]
dashu-float = { path = ".." }
criterion = "0.3"
rand = "0.8"

bigdecimal = "0.3"
twofloat = "0.5.0"
num-bigfloat = "1.3.1"
rug = "1.17.0"
