[package]
name = "bench"
version = "0.0.0"
publish = false
edition = "2021"

[[bench]]
name = "bench"
harness = false

[dependencies]
dashu-ratio = { path = ".." }
criterion = "0.3"
rand = "0.8"

num-rational = "0.4.1"
malachite-q = "0.3"
rug = "1.17.0"
