[package]
name = "dashu-python"
version = "0.0.1"
authors = ["Jacob Zhong <cmpute@gmail.com>"]
edition = "2024"
description = "Python binding for the dashu numeric types"
keywords = ["mathematics", "numerics"]
categories = ["mathematics", "science"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/cmpute/dashu"
homepage = "https://github.com/cmpute/dashu"
documentation = "https://docs.rs/dashu-python"
readme = "README.md"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true

[dependencies]
dashu-base = { version = "0.4.0", path = "../base", features = ["std"] }
dashu-int = { version = "0.4.1", path = "../integer", features = ["std", "num-order"] }
dashu-float = { version = "0.4.2", path = "../float", features = ["std", "num-order"] }
dashu-ratio = { version = "0.4.1", path = "../rational", features = ["std", "num-order", "dashu-float"] }
dashu-cmplx = { version = "0.4.5", path = "../complex", features = ["std", "num-order"] }
num-order = "1.2.0"

[dependencies.pyo3]
version = "0.29"
features = ["extension-module"]

[lib]
name = "dashu"
crate-type = ["cdylib"]
