from typing import overload, Literal, Optional, Tuple, Iterable, Union

# A native Python number or any dashu number.
Number = Union[int, float, "UBig", "IBig", "FBig", "DBig", "RBig"]

# Sign of a number.
class Sign:
    Positive: Sign
    Negative: Sign


class Words:
    def __init__(self, obj: list[int] | Words) -> None: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> int: ...
    @overload
    def __getitem__(self, index: slice) -> Words: ...
    def __setitem__(self, index: int | slice, value: int | list[int] | Words) -> None: ...
    def __delitem__(self, index: int | slice) -> None: ...
    def __add__(self, other: list[int] | Words) -> Words: ...
    def __mul__(self, count: int) -> Words: ...


class UBig:
    def __init__(self, obj: int | str, radix: Optional[int] = ...) -> None: ...
    def unwrap(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> bool: ...
    @overload
    def __getitem__(self, index: slice) -> UBig: ...
    def __setitem__(self, index: int | slice, value: bool) -> None: ...
    def __delitem__(self, index: int | slice) -> None: ...
    def __int__(self) -> int: ...

    # arithmetic (cross-type dispatch)
    def __add__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __radd__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __sub__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __rsub__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __mul__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __rmul__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __truediv__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __rtruediv__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __floordiv__(self, other: int | UBig | IBig) -> UBig | IBig: ...
    def __rfloordiv__(self, other: int | UBig | IBig) -> UBig | IBig: ...
    def __mod__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __divmod__(self, other: int | UBig | IBig) -> tuple: ...
    def __pow__(self, exp: int | UBig, modulus: Optional[int | UBig] = ...) -> UBig: ...
    def __iadd__(self, other: UBig) -> None: ...
    def __isub__(self, other: UBig) -> None: ...
    def __imul__(self, other: UBig) -> None: ...
    def __iand__(self, other: UBig) -> None: ...
    def __ior__(self, other: UBig) -> None: ...
    def __ixor__(self, other: UBig) -> None: ...
    def __ilshift__(self, other: int) -> None: ...
    def __irshift__(self, other: int) -> None: ...
    def __pos__(self) -> UBig: ...
    def __neg__(self) -> IBig: ...
    def __abs__(self) -> UBig: ...
    def __lshift__(self, other: int) -> UBig: ...
    def __rshift__(self, other: int) -> UBig: ...
    def __and__(self, other: int | UBig | IBig) -> UBig: ...
    def __or__(self, other: int | UBig | IBig) -> UBig | IBig: ...
    def __xor__(self, other: int | UBig | IBig) -> UBig | IBig: ...
    # comparisons (cross-type)
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Number) -> bool: ...
    def __le__(self, other: Number) -> bool: ...
    def __gt__(self, other: Number) -> bool: ...
    def __ge__(self, other: Number) -> bool: ...

    # number theory & roots
    def sqrt(self) -> UBig: ...
    def cbrt(self) -> UBig: ...
    def nth_root(self, n: int) -> UBig: ...
    def sqr(self) -> UBig: ...
    def cubic(self) -> UBig: ...
    def ilog(self, base: UBig) -> int: ...
    def is_multiple_of(self, divisor: UBig) -> bool: ...
    def remove(self, factor: UBig) -> int: ...
    def gcd(self, other: UBig) -> UBig: ...
    def gcd_ext(self, other: UBig) -> tuple[UBig, IBig, IBig]: ...
    # bit operations
    def count_ones(self) -> int: ...
    def count_zeros(self) -> Optional[int]: ...
    def trailing_zeros(self) -> Optional[int]: ...
    def trailing_ones(self) -> Optional[int]: ...
    def is_power_of_two(self) -> bool: ...
    def next_power_of_two(self) -> UBig: ...
    # accessors
    def is_one(self) -> bool: ...
    @staticmethod
    def ones(n: int) -> UBig: ...
    # interop
    def to_words(self) -> Words: ...
    @staticmethod
    def from_words(words: list[int] | Words) -> UBig: ...
    def to_bytes(self, byteorder: Optional[Literal["little", "big"]] = ...) -> bytes: ...
    @staticmethod
    def from_bytes(bytes: bytes, byteorder: Optional[Literal["little", "big"]] = ...) -> UBig: ...
    def to_chunks(self, chunk_bits: int) -> tuple[UBig, ...]: ...
    @staticmethod
    def from_chunks(chunks: Iterable[UBig], chunk_bits: int) -> UBig: ...


class IBig:
    def __init__(self, obj: int | str, radix: Optional[int] = ...) -> None: ...
    def unwrap(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> bool: ...
    def __int__(self) -> int: ...
    # arithmetic, comparisons, in-place: same cross-type surface as UBig
    def __add__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __radd__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __sub__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __rsub__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __mul__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __rmul__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __truediv__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __rtruediv__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __floordiv__(self, other: int | UBig | IBig) -> IBig: ...
    def __rfloordiv__(self, other: int | UBig | IBig) -> IBig: ...
    def __mod__(self, other: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
    def __divmod__(self, other: int | UBig | IBig) -> tuple: ...
    def __pow__(self, exp: int | UBig, modulus: Optional[int | UBig] = ...) -> IBig: ...
    def __iadd__(self, other: IBig) -> None: ...
    def __isub__(self, other: IBig) -> None: ...
    def __imul__(self, other: IBig) -> None: ...
    def __iand__(self, other: IBig) -> None: ...
    def __ior__(self, other: IBig) -> None: ...
    def __ixor__(self, other: IBig) -> None: ...
    def __ilshift__(self, other: int) -> None: ...
    def __irshift__(self, other: int) -> None: ...
    def __pos__(self) -> IBig: ...
    def __neg__(self) -> IBig: ...
    def __abs__(self) -> IBig: ...
    def __invert__(self) -> IBig: ...
    def __lshift__(self, other: int) -> IBig: ...
    def __rshift__(self, other: int) -> IBig: ...
    def __and__(self, other: int | UBig | IBig) -> UBig | IBig: ...
    def __or__(self, other: int | UBig | IBig) -> UBig | IBig: ...
    def __xor__(self, other: int | UBig | IBig) -> UBig | IBig: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Number) -> bool: ...
    def __le__(self, other: Number) -> bool: ...
    def __gt__(self, other: Number) -> bool: ...
    def __ge__(self, other: Number) -> bool: ...
    # number theory & roots
    def sqrt(self) -> UBig: ...
    def cbrt(self) -> IBig: ...
    def nth_root(self, n: int) -> IBig: ...
    def sqr(self) -> UBig: ...
    def cubic(self) -> IBig: ...
    def ilog(self, base: UBig) -> int: ...
    def trailing_zeros(self) -> Optional[int]: ...
    def trailing_ones(self) -> Optional[int]: ...
    def is_one(self) -> bool: ...
    def sign(self) -> Sign: ...
    def signum(self) -> IBig: ...
    def is_negative(self) -> bool: ...
    def is_positive(self) -> bool: ...
    def to_parts(self) -> tuple[Sign, UBig]: ...
    @staticmethod
    def from_parts(sign: Sign, magnitude: UBig) -> IBig: ...
    def as_ubig(self) -> Optional[UBig]: ...
    @staticmethod
    def ones(n: int) -> IBig: ...
    def to_words(self) -> Words: ...
    @staticmethod
    def from_words(words: list[int] | Words) -> IBig: ...
    def to_chunks(self, chunk_bits: int) -> tuple[UBig, ...]: ...
    @staticmethod
    def from_chunks(chunks: Iterable[UBig], chunk_bits: int) -> IBig: ...
    def to_bytes(
        self, byteorder: Optional[Literal["little", "big"]] = ..., signed: Optional[bool] = ...
    ) -> bytes: ...
    @staticmethod
    def from_bytes(
        bytes: bytes,
        byteorder: Optional[Literal["little", "big"]] = ...,
        signed: Optional[bool] = ...,
    ) -> IBig: ...


class FBig:
    def __init__(self, obj: float | int | str | "FBig") -> None: ...
    def unwrap(self) -> tuple[IBig, int]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __add__(self, other: Number) -> FBig: ...
    def __radd__(self, other: Number) -> FBig: ...
    def __sub__(self, other: Number) -> FBig: ...
    def __rsub__(self, other: Number) -> FBig: ...
    def __mul__(self, other: Number) -> FBig: ...
    def __rmul__(self, other: Number) -> FBig: ...
    def __truediv__(self, other: Number) -> FBig: ...
    def __rtruediv__(self, other: Number) -> FBig: ...
    def __mod__(self, other: Number) -> FBig: ...
    def __rmod__(self, other: Number) -> FBig: ...
    def __neg__(self) -> FBig: ...
    def __pos__(self) -> FBig: ...
    def __abs__(self) -> FBig: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Number) -> bool: ...
    def __le__(self, other: Number) -> bool: ...
    def __gt__(self, other: Number) -> bool: ...
    def __ge__(self, other: Number) -> bool: ...
    # predicates & sign
    def is_zero(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def is_infinite(self) -> bool: ...
    def sign(self) -> Sign: ...
    # rounding
    def trunc(self) -> FBig: ...
    def floor(self) -> FBig: ...
    def ceil(self) -> FBig: ...
    def round(self) -> FBig: ...
    def fract(self) -> FBig: ...
    # precision & parts
    def precision(self) -> int: ...
    def digits(self) -> int: ...
    def with_precision(self, precision: int) -> FBig: ...
    @staticmethod
    def from_parts(significand: IBig, exponent: int) -> FBig: ...
    # conversions
    def to_int(self) -> IBig: ...
    def to_decimal(self) -> DBig: ...
    def to_binary(self) -> FBig: ...
    def to_rational(self) -> RBig: ...
    # transcendentals (panic-free; domain errors raise ValueError)
    def sin(self) -> FBig: ...
    def cos(self) -> FBig: ...
    def tan(self) -> FBig: ...
    def asin(self) -> FBig: ...
    def acos(self) -> FBig: ...
    def atan(self) -> FBig: ...
    def atan2(self, x: FBig) -> FBig: ...
    def sinh(self) -> FBig: ...
    def cosh(self) -> FBig: ...
    def tanh(self) -> FBig: ...
    def asinh(self) -> FBig: ...
    def acosh(self) -> FBig: ...
    def atanh(self) -> FBig: ...
    def exp(self) -> FBig: ...
    def exp_m1(self) -> FBig: ...
    def ln(self) -> FBig: ...
    def ln_1p(self) -> FBig: ...
    def sqrt(self) -> FBig: ...
    def cbrt(self) -> FBig: ...
    def nth_root(self, n: int) -> FBig: ...
    def powf(self, w: FBig) -> FBig: ...
    def powi(self, n: IBig) -> FBig: ...


class DBig:
    def __init__(self, obj: float | int | str | "DBig") -> None: ...
    def unwrap(self) -> object: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __add__(self, other: Number) -> DBig: ...
    def __radd__(self, other: Number) -> DBig: ...
    def __sub__(self, other: Number) -> DBig: ...
    def __rsub__(self, other: Number) -> DBig: ...
    def __mul__(self, other: Number) -> DBig: ...
    def __rmul__(self, other: Number) -> DBig: ...
    def __truediv__(self, other: Number) -> DBig: ...
    def __rtruediv__(self, other: Number) -> DBig: ...
    def __mod__(self, other: Number) -> DBig: ...
    def __rmod__(self, other: Number) -> DBig: ...
    def __neg__(self) -> DBig: ...
    def __pos__(self) -> DBig: ...
    def __abs__(self) -> DBig: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Number) -> bool: ...
    def __le__(self, other: Number) -> bool: ...
    def __gt__(self, other: Number) -> bool: ...
    def __ge__(self, other: Number) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def is_infinite(self) -> bool: ...
    def sign(self) -> Sign: ...
    def trunc(self) -> DBig: ...
    def floor(self) -> DBig: ...
    def ceil(self) -> DBig: ...
    def round(self) -> DBig: ...
    def fract(self) -> DBig: ...
    def precision(self) -> int: ...
    def digits(self) -> int: ...
    def with_precision(self, precision: int) -> DBig: ...
    @staticmethod
    def from_parts(significand: IBig, exponent: int) -> DBig: ...
    def to_int(self) -> IBig: ...
    def to_decimal(self) -> DBig: ...
    def to_binary(self) -> FBig: ...
    def to_rational(self) -> RBig: ...
    # transcendentals (same set as FBig)
    def sin(self) -> DBig: ...
    def cos(self) -> DBig: ...
    def tan(self) -> DBig: ...
    def asin(self) -> DBig: ...
    def acos(self) -> DBig: ...
    def atan(self) -> DBig: ...
    def atan2(self, x: DBig) -> DBig: ...
    def sinh(self) -> DBig: ...
    def cosh(self) -> DBig: ...
    def tanh(self) -> DBig: ...
    def asinh(self) -> DBig: ...
    def acosh(self) -> DBig: ...
    def atanh(self) -> DBig: ...
    def exp(self) -> DBig: ...
    def exp_m1(self) -> DBig: ...
    def ln(self) -> DBig: ...
    def ln_1p(self) -> DBig: ...
    def sqrt(self) -> DBig: ...
    def cbrt(self) -> DBig: ...
    def nth_root(self, n: int) -> DBig: ...
    def powf(self, w: DBig) -> DBig: ...
    def powi(self, n: IBig) -> DBig: ...


class RBig:
    def __init__(self, obj: int | float | str | "RBig") -> None: ...
    def unwrap(self) -> object: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __add__(self, other: Number) -> RBig: ...
    def __radd__(self, other: Number) -> RBig: ...
    def __sub__(self, other: Number) -> RBig: ...
    def __rsub__(self, other: Number) -> RBig: ...
    def __mul__(self, other: Number) -> RBig: ...
    def __rmul__(self, other: Number) -> RBig: ...
    def __truediv__(self, other: Number) -> RBig: ...
    def __rtruediv__(self, other: Number) -> RBig: ...
    def __mod__(self, other: Number) -> RBig: ...
    def __rmod__(self, other: Number) -> RBig: ...
    def __neg__(self) -> RBig: ...
    def __pos__(self) -> RBig: ...
    def __abs__(self) -> RBig: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Number) -> bool: ...
    def __le__(self, other: Number) -> bool: ...
    def __gt__(self, other: Number) -> bool: ...
    def __ge__(self, other: Number) -> bool: ...
    @property
    def numerator(self) -> IBig: ...
    @property
    def denominator(self) -> UBig: ...
    def is_int(self) -> bool: ...
    def is_one(self) -> bool: ...
    def sign(self) -> Sign: ...
    def signum(self) -> RBig: ...
    def trunc(self) -> IBig: ...
    def floor(self) -> IBig: ...
    def ceil(self) -> IBig: ...
    def round(self) -> IBig: ...
    def fract(self) -> RBig: ...
    def split_at_point(self) -> tuple[IBig, RBig]: ...
    def sqr(self) -> RBig: ...
    def cubic(self) -> RBig: ...
    def pow(self, n: int) -> RBig: ...
    def to_int(self) -> IBig: ...
    def to_float(self, precision: int) -> FBig: ...
    def to_decimal(self, precision: int) -> DBig: ...
    @staticmethod
    def from_parts(numerator: IBig, denominator: UBig) -> RBig: ...
    @staticmethod
    def simplest_from_float(f: FBig) -> Optional[RBig]: ...


class CBig:
    def __init__(
        self, re: float | int | str | FBig | "CBig" | complex, im: Optional[float | int | FBig] = ...
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __complex__(self) -> complex: ...
    def __add__(self, other: float | int | FBig | CBig | complex) -> CBig: ...
    def __radd__(self, other: float | int | FBig | complex) -> CBig: ...
    def __sub__(self, other: float | int | FBig | CBig | complex) -> CBig: ...
    def __rsub__(self, other: float | int | FBig | complex) -> CBig: ...
    def __mul__(self, other: float | int | FBig | CBig | complex) -> CBig: ...
    def __rmul__(self, other: float | int | FBig | complex) -> CBig: ...
    def __truediv__(self, other: float | int | FBig | CBig | complex) -> CBig: ...
    def __rtruediv__(self, other: float | int | FBig | complex) -> CBig: ...
    def __neg__(self) -> CBig: ...
    def __pos__(self) -> CBig: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def real(self) -> FBig: ...
    def imag(self) -> FBig: ...
    def precision(self) -> int: ...
    def is_zero(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def is_infinite(self) -> bool: ...
    def conj(self) -> CBig: ...
    def proj(self) -> CBig: ...
    def norm(self) -> FBig: ...
    def abs(self) -> FBig: ...
    def arg(self) -> FBig: ...
    @staticmethod
    def from_parts(re: FBig, im: FBig) -> CBig: ...
    def sin(self) -> CBig: ...
    def cos(self) -> CBig: ...
    def tan(self) -> CBig: ...
    def exp(self) -> CBig: ...
    def ln(self) -> CBig: ...
    def sqrt(self) -> CBig: ...
    def powi(self, n: IBig) -> CBig: ...
    def powf(self, w: CBig) -> CBig: ...


class Cache:
    @staticmethod
    def clear() -> None: ...
    @staticmethod
    def total_terms() -> int: ...
    @staticmethod
    def total_words() -> int: ...


# module-level math functions (transcendentals are panic-free; domain errors raise ValueError)
def auto(obj: Number) -> "UBig|IBig|FBig|DBig|RBig": ...
def autos(s: str) -> "UBig|IBig|FBig|DBig|RBig": ...

def sin(x: FBig) -> FBig: ...
def cos(x: FBig) -> FBig: ...
def tan(x: FBig) -> FBig: ...
def asin(x: FBig) -> FBig: ...
def acos(x: FBig) -> FBig: ...
def atan(x: FBig) -> FBig: ...
def atan2(y: FBig, x: FBig) -> FBig: ...
def sinh(x: FBig) -> FBig: ...
def cosh(x: FBig) -> FBig: ...
def tanh(x: FBig) -> FBig: ...
def asinh(x: FBig) -> FBig: ...
def acosh(x: FBig) -> FBig: ...
def atanh(x: FBig) -> FBig: ...
def exp(x: FBig) -> FBig: ...
def expm1(x: FBig) -> FBig: ...
def log(x: FBig) -> FBig: ...
def log1p(x: FBig) -> FBig: ...
def ln(x: FBig) -> FBig: ...
def ln_1p(x: FBig) -> FBig: ...
def sqrt(x: FBig) -> FBig: ...
def cbrt(x: FBig) -> FBig: ...
def nth_root(x: FBig, n: int) -> FBig: ...
def powf(x: FBig, y: FBig) -> FBig: ...
def powi(x: FBig, n: IBig) -> FBig: ...
def hypot(x: FBig, y: FBig) -> FBig: ...
def gcd(a: UBig, b: UBig) -> UBig: ...
def gcd_ext(a: UBig, b: UBig) -> tuple[UBig, IBig, IBig]: ...
def lcm(a: UBig, b: UBig) -> UBig: ...
